name: Test CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev or qa)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
      browser:
        description: 'Select browser (chrome or firefox)'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox

env:
  DEFAULT_ENV: dev
  DEFAULT_BROWSER: chrome

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Clean previous test results
        run: rm -rf build/test-results/* build/reports/tests/customTest/* || true

      - name: Run PMD
        run: ./gradlew pmdMain pmdTest

      - name: Run smoke tests
        run: ./gradlew customTest -PsuiteType=smoke -Denv=${{ github.event.inputs.environment || env.DEFAULT_ENV }} -Dbrowser=${{ github.event.inputs.browser || env.DEFAULT_BROWSER }}

      - name: Upload smoke test results as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results
          path: build/reports/tests/customTest

      - name: Upload screenshots for smoke tests
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-screenshots
          path: build/reports/tests/screenshots

      - name: Smoke Tests Summary
        uses: test-summary/action@dist
        with:
          paths: build/reports/tests/customTest/*.xml
        if: always()

  # previsous implementation

      - name: Clean previous test results
        run: rm -rf build/test-results/* build/reports/tests/customTest/* || true

      - name: Run regression tests
        run: ./gradlew -i customTest -PsuiteType=regression -Denv=${{ github.event.inputs.environment || env.DEFAULT_ENV }} -Dbrowser=${{ github.event.inputs.browser || env.DEFAULT_BROWSER }}

      - name: Upload regression test results as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-test-results
          path: build/reports/tests/customTest

      - name: Upload screenshots for regression tests
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: regression-test-screenshots
          path: build/reports/tests/screenshots

      - name: Add Regression Test Summary to Job Summary
        run: |
          echo "### Regression Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          ./gradlew testReport --tests "*regression*" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

permissions:
  id-token: write
  contents: read
  checks: write
  actions: write