name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      environment:
        description: 'Select environment (dev or qa)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
      browser:
        description: 'Select browser (chrome or firefox)'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
env:
  DEFAULT_ENV: dev
  DEFAULT_BROWSER: chrome

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Spotless Check # code formatter
        run: ./gradlew spotlessCheck

      - name: Run PMD
        run: ./gradlew pmdMain pmdTest

      - name: Upload PMD report as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: build/reports/pmd/

      - name: Upload PMD report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: PMD Report
          path: build/reports/pmd/*.xml
          reporter: java-junit
          fail-on-error: false

      - name: Run smoke tests
        run: ./gradlew customTest -PsuiteType=smoke -Denv=${{ github.event.inputs.environment || env.DEFAULT_ENV }} -Dbrowser=${{ github.event.inputs.browser || env.DEFAULT_BROWSER  }}

      - name: Upload smoke test results as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results
          path: build/reports/tests/customTest

      - name: Test report smoke tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Smoke Tests
          path: build/test-results/customTest/*.xml
          reporter: java-junit
          fail-on-error: false

      - name: Clean build directory
        run: ./gradlew cleanBuildDir

      - name: Run regression tests
        run: ./gradlew customTest -PsuiteType=regression -Denv=${{ github.event.inputs.environment || env.DEFAULT_ENV }} -Dbrowser=${{ github.event.inputs.browser || env.DEFAULT_BROWSER  }}

      - name: Upload regression test results as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-test-results
          path: build/reports/tests/customTest

      - name: Test report regression tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Regression Tests
          path: build/test-results/customTest/*.xml
          reporter: java-junit
          fail-on-error: false

permissions:
  id-token: write
  contents: read
  checks: write
  actions: write

