name: CI Pipeline

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      environment:
        description: 'Select environment (dev or qa)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
      browser:
        description: 'Select browser (chrome or firefox)'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox

env:
  DEFAULT_ENV: dev
  DEFAULT_BROWSER: chrome
  RUN_ID: ${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clean previous test results
        run: rm -rf build/test-results/* build/reports/tests/customTest/* || true

      - name: Run smoke tests
        run: ./gradlew customTest -PsuiteType=smoke -Denv=${{ github.event.inputs.environment || env.DEFAULT_ENV }} -Dbrowser=${{ github.event.inputs.browser || env.DEFAULT_BROWSER }}

      - name: Test report smoke tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Smoke Tests - Run ${{ env.RUN_ID }}
          path: build/test-results/customTest/*.xml
          reporter: java-junit
          fail-on-error: false

      - name: Run regression tests
        run: ./gradlew customTest -PsuiteType=regression -Denv=${{ github.event.inputs.environment || env.DEFAULT_ENV }} -Dbrowser=${{ github.event.inputs.browser || env.DEFAULT_BROWSER }}

      - name: Test report regression tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Regression Tests - Run ${{ env.RUN_ID }}
          path: build/test-results/customTest/*.xml
          reporter: java-junit
          fail-on-error: false

permissions:
  id-token: write
  contents: read
  checks: write
  actions: write